name: demo-action
description: 'Simple action demo'
author: mchmarny
branding:
  icon: arrow-up
  color: gray-dark
inputs:
  file:
    description: 'File path'
    required: true
  required:
    description: 'Whether or not it is required'
    required: false
    default: "false"
outputs:
  output:
    description: 'The main output of this action'
  processed_on:
    description: 'The time when this action was processed'

runs:
  using: docker
  image: docker://ghcr.io/mchmarny/action:latest  # pinned to digest in real use
